### ISSUE TITLE
Des poids NaN apparaîssent pendant l'entraînement

### ISSUE THREAD

**Issue by sofian** [a3lab/morphoses#18]
Il y a des situations où des poids de valeur NaN apparaîssent pendant l'entraînement. eg.

```python3 rl_curiosity.py --n-action-bins 3 --use-delta-euler --reward-inv-delta-pitch --reward-delta-roll --curiosity-weight 0.0 --model tables --n-state-tiles 5 --n-state-tilings 5 --send-port 7765 --receive-port 7767 --use-robot --time-step 1 --learning-rate 0.1 --policy mixed --temperature 0.5 --gamma 0.7 --epsilon 0.1 -nf 32```

```
qsum: [0.         5.05444394 0.         0.         0.                nan
 0.         1.50163859 1.62533037]
Prediction: [nan nan nan nan nan nan nan nan nan]
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58172)
Traceback (most recent call last):
  File "/usr/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/tats/.local/lib/python3.8/site-packages/pythonosc/osc_server.py", line 29, in handle
    self.server.dispatcher.call_handlers_for_packet(self.request[0], self.client_address)
  File "/home/tats/.local/lib/python3.8/site-packages/pythonosc/dispatcher.py", line 194, in call_handlers_for_packet
    handler.invoke(client_address, timed_msg.message)
  File "/home/tats/.local/lib/python3.8/site-packages/pythonosc/dispatcher.py", line 57, in invoke
    self.callback(message.address, *message)
  File "rl_curiosity.py", line 574, in handle_data
    action = choose_action_softmax(prediction, temperature)
  File "rl_curiosity.py", line 224, in choose_action_softmax
    return np.asscalar(np.random.choice(np.arange(len(prediction)), 1, p=prediction))
  File "mtrand.pyx", line 793, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities contain NaN
----------------------------------------
```

**Comment by sofian** [comment]
Ceci est un vieux problème qui semble avoir été corrigé.
